// TCS Foundation Test Questions
// 65 questions total: 25 Numerical, 20 Verbal, 20 Reasoning

export interface QuestionData {
    id: string;
    text: string;
    type: 'multiple-choice';
    category: 'numerical' | 'verbal' | 'reasoning';
    options: {
        text: string;
        isCorrect: boolean;
    }[];
}

export const tcsFoundationQuestions: QuestionData[] = [
    // NUMERICAL ABILITY (25 questions)
    {
        id: 'tcs-f-n-1',
        text: 'If a train travels 120 km in 2 hours, what is its average speed?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '50 km/h', isCorrect: false },
            { text: '60 km/h', isCorrect: true },
            { text: '70 km/h', isCorrect: false },
            { text: '80 km/h', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-2',
        text: 'What is 15% of 200?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '25', isCorrect: false },
            { text: '30', isCorrect: true },
            { text: '35', isCorrect: false },
            { text: '40', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-3',
        text: 'If x + 5 = 12, what is the value of x?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '5', isCorrect: false },
            { text: '6', isCorrect: false },
            { text: '7', isCorrect: true },
            { text: '8', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-4',
        text: 'The average of 5 numbers is 20. If one number is 30, what is the sum of the other 4 numbers?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '60', isCorrect: false },
            { text: '70', isCorrect: true },
            { text: '80', isCorrect: false },
            { text: '90', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-5',
        text: 'A shopkeeper sells an item at 20% profit. If the cost price is ₹500, what is the selling price?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '₹550', isCorrect: false },
            { text: '₹600', isCorrect: true },
            { text: '₹650', isCorrect: false },
            { text: '₹700', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-6',
        text: 'What is the next number in the series: 2, 4, 8, 16, ?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '24', isCorrect: false },
            { text: '28', isCorrect: false },
            { text: '32', isCorrect: true },
            { text: '36', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-7',
        text: 'If 3x - 7 = 14, what is x?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '5', isCorrect: false },
            { text: '6', isCorrect: false },
            { text: '7', isCorrect: true },
            { text: '8', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-8',
        text: 'A rectangle has length 10 cm and width 5 cm. What is its area?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '40 cm²', isCorrect: false },
            { text: '45 cm²', isCorrect: false },
            { text: '50 cm²', isCorrect: true },
            { text: '55 cm²', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-9',
        text: 'If the ratio of boys to girls in a class is 3:2 and there are 15 boys, how many girls are there?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '8', isCorrect: false },
            { text: '9', isCorrect: false },
            { text: '10', isCorrect: true },
            { text: '12', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-10',
        text: 'What is 25% of 80?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '15', isCorrect: false },
            { text: '20', isCorrect: true },
            { text: '25', isCorrect: false },
            { text: '30', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-11',
        text: 'A car travels 240 km in 4 hours. What is its speed in km/h?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '50', isCorrect: false },
            { text: '55', isCorrect: false },
            { text: '60', isCorrect: true },
            { text: '65', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-12',
        text: 'If 2/5 of a number is 40, what is the number?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '80', isCorrect: false },
            { text: '90', isCorrect: false },
            { text: '100', isCorrect: true },
            { text: '110', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-13',
        text: 'The sum of three consecutive numbers is 60. What is the middle number?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '18', isCorrect: false },
            { text: '19', isCorrect: false },
            { text: '20', isCorrect: true },
            { text: '21', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-14',
        text: 'What is the compound interest on ₹1000 at 10% per annum for 2 years?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '₹200', isCorrect: false },
            { text: '₹210', isCorrect: true },
            { text: '₹220', isCorrect: false },
            { text: '₹230', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-15',
        text: 'If a:b = 2:3 and b:c = 4:5, what is a:c?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '6:15', isCorrect: false },
            { text: '8:15', isCorrect: true },
            { text: '10:15', isCorrect: false },
            { text: '12:15', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-16',
        text: 'A pipe can fill a tank in 6 hours. What fraction of the tank will it fill in 2 hours?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '1/4', isCorrect: false },
            { text: '1/3', isCorrect: true },
            { text: '1/2', isCorrect: false },
            { text: '2/3', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-17',
        text: 'What is the LCM of 12 and 18?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '24', isCorrect: false },
            { text: '36', isCorrect: true },
            { text: '48', isCorrect: false },
            { text: '54', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-18',
        text: 'If 5 workers can complete a job in 12 days, how many days will 10 workers take?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '4 days', isCorrect: false },
            { text: '6 days', isCorrect: true },
            { text: '8 days', isCorrect: false },
            { text: '10 days', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-19',
        text: 'What is the value of (15 + 5) × 2?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '30', isCorrect: false },
            { text: '35', isCorrect: false },
            { text: '40', isCorrect: true },
            { text: '45', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-20',
        text: 'A discount of 10% on ₹500 is equal to:',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '₹40', isCorrect: false },
            { text: '₹45', isCorrect: false },
            { text: '₹50', isCorrect: true },
            { text: '₹55', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-21',
        text: 'If x² = 64, what is the positive value of x?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '6', isCorrect: false },
            { text: '7', isCorrect: false },
            { text: '8', isCorrect: true },
            { text: '9', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-22',
        text: 'The perimeter of a square is 40 cm. What is the length of one side?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '8 cm', isCorrect: false },
            { text: '10 cm', isCorrect: true },
            { text: '12 cm', isCorrect: false },
            { text: '15 cm', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-23',
        text: 'What is 3/4 + 1/2?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '1', isCorrect: false },
            { text: '5/4', isCorrect: true },
            { text: '3/2', isCorrect: false },
            { text: '7/4', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-24',
        text: 'If a book costs ₹120 after a 20% discount, what was the original price?',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '₹140', isCorrect: false },
            { text: '₹150', isCorrect: true },
            { text: '₹160', isCorrect: false },
            { text: '₹170', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-n-25',
        text: 'What is the area of a circle with radius 7 cm? (Use π = 22/7)',
        type: 'multiple-choice',
        category: 'numerical',
        options: [
            { text: '144 cm²', isCorrect: false },
            { text: '154 cm²', isCorrect: true },
            { text: '164 cm²', isCorrect: false },
            { text: '174 cm²', isCorrect: false },
        ],
    },

    // VERBAL ABILITY (20 questions)
    {
        id: 'tcs-f-v-1',
        text: 'Choose the synonym of "ABUNDANT":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Scarce', isCorrect: false },
            { text: 'Plentiful', isCorrect: true },
            { text: 'Rare', isCorrect: false },
            { text: 'Limited', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-2',
        text: 'Choose the antonym of "BRAVE":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Courageous', isCorrect: false },
            { text: 'Bold', isCorrect: false },
            { text: 'Cowardly', isCorrect: true },
            { text: 'Fearless', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-3',
        text: 'Fill in the blank: She is _____ intelligent than her sister.',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'more', isCorrect: true },
            { text: 'most', isCorrect: false },
            { text: 'much', isCorrect: false },
            { text: 'many', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-4',
        text: 'Identify the correctly spelled word:',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Occassion', isCorrect: false },
            { text: 'Occasion', isCorrect: true },
            { text: 'Ocassion', isCorrect: false },
            { text: 'Ocasion', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-5',
        text: 'Choose the correct sentence:',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'He don\'t like coffee.', isCorrect: false },
            { text: 'He doesn\'t likes coffee.', isCorrect: false },
            { text: 'He doesn\'t like coffee.', isCorrect: true },
            { text: 'He don\'t likes coffee.', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-6',
        text: 'What is the meaning of the idiom "Break the ice"?',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'To start a conversation', isCorrect: true },
            { text: 'To break something', isCorrect: false },
            { text: 'To feel cold', isCorrect: false },
            { text: 'To end a relationship', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-7',
        text: 'Choose the synonym of "DILIGENT":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Lazy', isCorrect: false },
            { text: 'Careless', isCorrect: false },
            { text: 'Hardworking', isCorrect: true },
            { text: 'Negligent', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-8',
        text: 'Fill in the blank: Neither of the students _____ completed the assignment.',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'have', isCorrect: false },
            { text: 'has', isCorrect: true },
            { text: 'are', isCorrect: false },
            { text: 'were', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-9',
        text: 'Choose the antonym of "GENEROUS":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Kind', isCorrect: false },
            { text: 'Selfish', isCorrect: true },
            { text: 'Charitable', isCorrect: false },
            { text: 'Benevolent', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-10',
        text: 'Identify the part of speech of the underlined word: She runs "quickly".',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Noun', isCorrect: false },
            { text: 'Verb', isCorrect: false },
            { text: 'Adjective', isCorrect: false },
            { text: 'Adverb', isCorrect: true },
        ],
    },
    {
        id: 'tcs-f-v-11',
        text: 'Choose the correct preposition: She is good _____ mathematics.',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'in', isCorrect: false },
            { text: 'at', isCorrect: true },
            { text: 'on', isCorrect: false },
            { text: 'with', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-12',
        text: 'What is the plural of "Child"?',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Childs', isCorrect: false },
            { text: 'Children', isCorrect: true },
            { text: 'Childes', isCorrect: false },
            { text: 'Childrens', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-13',
        text: 'Choose the synonym of "ANCIENT":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Modern', isCorrect: false },
            { text: 'New', isCorrect: false },
            { text: 'Old', isCorrect: true },
            { text: 'Recent', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-14',
        text: 'Fill in the blank: If I _____ you, I would accept the offer.',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'am', isCorrect: false },
            { text: 'was', isCorrect: false },
            { text: 'were', isCorrect: true },
            { text: 'be', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-15',
        text: 'What does "Once in a blue moon" mean?',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Very often', isCorrect: false },
            { text: 'Very rarely', isCorrect: true },
            { text: 'Never', isCorrect: false },
            { text: 'Always', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-16',
        text: 'Choose the correctly punctuated sentence:',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Lets eat grandma!', isCorrect: false },
            { text: 'Let\'s eat, grandma!', isCorrect: true },
            { text: 'Lets eat, grandma', isCorrect: false },
            { text: 'Let\'s eat grandma', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-17',
        text: 'Choose the antonym of "EXPAND":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Grow', isCorrect: false },
            { text: 'Increase', isCorrect: false },
            { text: 'Contract', isCorrect: true },
            { text: 'Enlarge', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-18',
        text: 'Fill in the blank: The book _____ on the table.',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'is', isCorrect: true },
            { text: 'are', isCorrect: false },
            { text: 'were', isCorrect: false },
            { text: 'be', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-19',
        text: 'Choose the synonym of "VIVID":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Dull', isCorrect: false },
            { text: 'Bright', isCorrect: true },
            { text: 'Faint', isCorrect: false },
            { text: 'Pale', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-v-20',
        text: 'Identify the error: "She have been working here since 2020."',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'have should be has', isCorrect: true },
            { text: 'been should be being', isCorrect: false },
            { text: 'since should be from', isCorrect: false },
            { text: 'No error', isCorrect: false },
        ],
    },

    // REASONING (20 questions)
    {
        id: 'tcs-f-r-1',
        text: 'If all roses are flowers and some flowers are red, which statement is definitely true?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'All roses are red', isCorrect: false },
            { text: 'Some roses are red', isCorrect: false },
            { text: 'All flowers are roses', isCorrect: false },
            { text: 'Some flowers are roses', isCorrect: true },
        ],
    },
    {
        id: 'tcs-f-r-2',
        text: 'Complete the series: A, C, E, G, ?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'H', isCorrect: false },
            { text: 'I', isCorrect: true },
            { text: 'J', isCorrect: false },
            { text: 'K', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-3',
        text: 'If CODING is written as DPEJOH, how is BRAIN written?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'CSBJO', isCorrect: true },
            { text: 'AQZHM', isCorrect: false },
            { text: 'DSBJO', isCorrect: false },
            { text: 'CQBJO', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-4',
        text: 'Find the odd one out: 3, 5, 7, 9, 12',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: '3', isCorrect: false },
            { text: '5', isCorrect: false },
            { text: '9', isCorrect: false },
            { text: '12', isCorrect: true },
        ],
    },
    {
        id: 'tcs-f-r-5',
        text: 'If South-East becomes North, North-East becomes West and so on, what does South become?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'North-East', isCorrect: false },
            { text: 'North-West', isCorrect: true },
            { text: 'South-East', isCorrect: false },
            { text: 'South-West', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-6',
        text: 'In a certain code, MONKEY is written as XDJMNL. How is TIGER written?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'SHFDQ', isCorrect: false },
            { text: 'UJHFS', isCorrect: false },
            { text: 'SDFHS', isCorrect: true },
            { text: 'SHFDS', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-7',
        text: 'What comes next in the pattern: 1, 4, 9, 16, ?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: '20', isCorrect: false },
            { text: '24', isCorrect: false },
            { text: '25', isCorrect: true },
            { text: '30', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-8',
        text: 'If A is the father of B, but B is not the son of A, what is B to A?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'Nephew', isCorrect: false },
            { text: 'Daughter', isCorrect: true },
            { text: 'Niece', isCorrect: false },
            { text: 'Sister', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-9',
        text: 'Find the missing number: 2, 6, 12, 20, 30, ?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: '38', isCorrect: false },
            { text: '40', isCorrect: false },
            { text: '42', isCorrect: true },
            { text: '44', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-10',
        text: 'If CAT = 24, DOG = 26, what is BIRD?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: '30', isCorrect: false },
            { text: '32', isCorrect: true },
            { text: '34', isCorrect: false },
            { text: '36', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-11',
        text: 'Complete the analogy: Book : Pages :: Tree : ?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'Forest', isCorrect: false },
            { text: 'Branches', isCorrect: true },
            { text: 'Roots', isCorrect: false },
            { text: 'Leaves', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-12',
        text: 'Which number should replace the question mark: 3, 7, 15, 31, ?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: '55', isCorrect: false },
            { text: '59', isCorrect: false },
            { text: '63', isCorrect: true },
            { text: '67', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-13',
        text: 'If you rearrange the letters "CIFAIPC", you would have the name of a(n):',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'City', isCorrect: false },
            { text: 'Animal', isCorrect: false },
            { text: 'Ocean', isCorrect: true },
            { text: 'Country', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-14',
        text: 'Find the odd one out: Triangle, Square, Circle, Rectangle, Pentagon',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'Triangle', isCorrect: false },
            { text: 'Square', isCorrect: false },
            { text: 'Circle', isCorrect: true },
            { text: 'Pentagon', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-15',
        text: 'If 1st January 2020 was Wednesday, what day was 1st January 2021?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'Thursday', isCorrect: false },
            { text: 'Friday', isCorrect: true },
            { text: 'Saturday', isCorrect: false },
            { text: 'Sunday', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-16',
        text: 'Complete the series: Z, Y, X, W, V, ?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'T', isCorrect: false },
            { text: 'U', isCorrect: true },
            { text: 'S', isCorrect: false },
            { text: 'R', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-17',
        text: 'If FRIEND is coded as HUMJTK, how is CANDLE coded?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'EDRIRL', isCorrect: false },
            { text: 'ECSNJG', isCorrect: true },
            { text: 'DCQHMC', isCorrect: false },
            { text: 'EDRPNG', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-18',
        text: 'What is the next term: 5, 10, 20, 40, ?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: '60', isCorrect: false },
            { text: '70', isCorrect: false },
            { text: '80', isCorrect: true },
            { text: '90', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-19',
        text: 'Complete the analogy: Doctor : Hospital :: Teacher : ?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'Student', isCorrect: false },
            { text: 'School', isCorrect: true },
            { text: 'Book', isCorrect: false },
            { text: 'Classroom', isCorrect: false },
        ],
    },
    {
        id: 'tcs-f-r-20',
        text: 'If in a code language, ROSE is written as TQUG, how is LILY written?',
        type: 'multiple-choice',
        category: 'reasoning',
        options: [
            { text: 'NKNA', isCorrect: true },
            { text: 'MJMX', isCorrect: false },
            { text: 'NJNA', isCorrect: false },
            { text: 'MKNA', isCorrect: false },
        ],
    },
];
