// Wipro Aptitude Test Questions
// 48 questions total: 16 Quant, 16 Logical, 16 Verbal

export interface QuestionData {
    id: string;
    text: string;
    type: 'multiple-choice';
    category: 'quant' | 'logical' | 'verbal';
    options: {
        text: string;
        isCorrect: boolean;
    }[];
}

export const wiproAptitudeQuestions: QuestionData[] = [
    // QUANTITATIVE (16 questions)
    {
        id: 'wipro-apt-q-1',
        text: 'If a number is increased by 20% and then decreased by 20%, the net change is:',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: 'No change', isCorrect: false },
            { text: '4% decrease', isCorrect: true },
            { text: '4% increase', isCorrect: false },
            { text: '2% decrease', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-2',
        text: 'The average of 5 consecutive odd numbers is 27. What is the largest number?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '29', isCorrect: false },
            { text: '31', isCorrect: true },
            { text: '33', isCorrect: false },
            { text: '35', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-3',
        text: 'A man buys 12 pens for ₹10 and sells 10 pens for ₹12. What is his profit percentage?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '40%', isCorrect: false },
            { text: '44%', isCorrect: true },
            { text: '48%', isCorrect: false },
            { text: '50%', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-4',
        text: 'If 20% of A = 30% of B, then A:B is:',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '2:3', isCorrect: false },
            { text: '3:2', isCorrect: true },
            { text: '1:1', isCorrect: false },
            { text: '4:3', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-5',
        text: 'A sum of money doubles itself in 8 years at simple interest. In how many years will it triple?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '12 years', isCorrect: false },
            { text: '16 years', isCorrect: true },
            { text: '20 years', isCorrect: false },
            { text: '24 years', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-6',
        text: 'The speed of a boat in still water is 15 km/h. If it can travel 30 km downstream in 2 hours, what is the speed of the stream?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '2 km/h', isCorrect: false },
            { text: '3 km/h', isCorrect: true },
            { text: '4 km/h', isCorrect: false },
            { text: '5 km/h', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-7',
        text: 'If x% of 75 = 15, what is the value of x?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '15', isCorrect: false },
            { text: '20', isCorrect: true },
            { text: '25', isCorrect: false },
            { text: '30', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-8',
        text: 'The ratio of ages of A and B is 3:5. After 6 years, the ratio will be 2:3. What is A\'s current age?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '12 years', isCorrect: false },
            { text: '15 years', isCorrect: false },
            { text: '18 years', isCorrect: true },
            { text: '21 years', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-9',
        text: 'A can complete a work in 12 days and B in 18 days. If they work together, in how many days will the work be completed?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '6 days', isCorrect: false },
            { text: '7.2 days', isCorrect: true },
            { text: '8 days', isCorrect: false },
            { text: '9 days', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-10',
        text: 'The area of a square is 144 cm². What is the length of its diagonal?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '12√2 cm', isCorrect: true },
            { text: '12 cm', isCorrect: false },
            { text: '14√2 cm', isCorrect: false },
            { text: '16 cm', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-11',
        text: 'If 3ˣ = 81, what is the value of x?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '3', isCorrect: false },
            { text: '4', isCorrect: true },
            { text: '5', isCorrect: false },
            { text: '6', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-12',
        text: 'The sum of three numbers is 98. The ratio of the first to the second is 2:3, and that of the second to the third is 5:8. What is the second number?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '20', isCorrect: false },
            { text: '25', isCorrect: false },
            { text: '30', isCorrect: true },
            { text: '35', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-13',
        text: 'A mixture of 40 liters contains milk and water in the ratio 3:1. How much water should be added to make the ratio 2:1?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '5 liters', isCorrect: true },
            { text: '10 liters', isCorrect: false },
            { text: '15 liters', isCorrect: false },
            { text: '20 liters', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-14',
        text: 'If the cost price of 20 articles is equal to the selling price of 16 articles, what is the profit percentage?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '20%', isCorrect: false },
            { text: '25%', isCorrect: true },
            { text: '30%', isCorrect: false },
            { text: '35%', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-15',
        text: 'A train travels 360 km at a uniform speed. If the speed had been 5 km/h more, it would have taken 1 hour less. What is the original speed?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '30 km/h', isCorrect: false },
            { text: '40 km/h', isCorrect: true },
            { text: '45 km/h', isCorrect: false },
            { text: '50 km/h', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-q-16',
        text: 'The average of 11 numbers is 50. If the average of the first 6 numbers is 49 and that of the last 6 numbers is 52, what is the 6th number?',
        type: 'multiple-choice',
        category: 'quant',
        options: [
            { text: '52', isCorrect: false },
            { text: '56', isCorrect: true },
            { text: '60', isCorrect: false },
            { text: '64', isCorrect: false },
        ],
    },

    // LOGICAL REASONING (16 questions)
    {
        id: 'wipro-apt-l-1',
        text: 'Complete the series: 2, 5, 10, 17, 26, ?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: '35', isCorrect: false },
            { text: '37', isCorrect: true },
            { text: '39', isCorrect: false },
            { text: '41', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-2',
        text: 'If COMPUTER is coded as RFUVQNPC, how is MACHINE coded?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: 'NBDJSFO', isCorrect: true },
            { text: 'NBDJTFO', isCorrect: false },
            { text: 'NCDJSFO', isCorrect: false },
            { text: 'NBCJSFO', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-3',
        text: 'Find the odd one out: 121, 144, 169, 196, 225',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: '121', isCorrect: false },
            { text: '144', isCorrect: false },
            { text: '196', isCorrect: true },
            { text: '225', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-4',
        text: 'If A is taller than B, B is taller than C, and C is taller than D, who is the shortest?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: 'A', isCorrect: false },
            { text: 'B', isCorrect: false },
            { text: 'C', isCorrect: false },
            { text: 'D', isCorrect: true },
        ],
    },
    {
        id: 'wipro-apt-l-5',
        text: 'Complete the pattern: ACE, BDF, CEG, ?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: 'DFH', isCorrect: true },
            { text: 'DEF', isCorrect: false },
            { text: 'EFG', isCorrect: false },
            { text: 'DGH', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-6',
        text: 'If Monday is 3 days after tomorrow, what day is today?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: 'Wednesday', isCorrect: false },
            { text: 'Thursday', isCorrect: false },
            { text: 'Friday', isCorrect: true },
            { text: 'Saturday', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-7',
        text: 'In a certain code, RAIN is written as 8$%6 and MORE is written as 7#8@. How is ROME written?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: '8#7@', isCorrect: true },
            { text: '8@7#', isCorrect: false },
            { text: '7#8@', isCorrect: false },
            { text: '7@8#', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-8',
        text: 'What comes next: 1, 1, 2, 3, 5, 8, 13, ?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: '18', isCorrect: false },
            { text: '19', isCorrect: false },
            { text: '20', isCorrect: false },
            { text: '21', isCorrect: true },
        ],
    },
    {
        id: 'wipro-apt-l-9',
        text: 'A clock shows 9:00. What is the angle between the hour and minute hands?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: '80°', isCorrect: false },
            { text: '85°', isCorrect: false },
            { text: '90°', isCorrect: true },
            { text: '95°', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-10',
        text: 'If BAT = 23, CAT = 24, what is RAT?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: '39', isCorrect: true },
            { text: '40', isCorrect: false },
            { text: '41', isCorrect: false },
            { text: '42', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-11',
        text: 'Complete the analogy: Pen : Write :: Knife : ?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: 'Sharp', isCorrect: false },
            { text: 'Cut', isCorrect: true },
            { text: 'Blade', isCorrect: false },
            { text: 'Kitchen', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-12',
        text: 'Find the missing number: 3, 6, 11, 18, 27, ?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: '36', isCorrect: false },
            { text: '37', isCorrect: false },
            { text: '38', isCorrect: true },
            { text: '39', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-13',
        text: 'If DELHI is coded as CCIDD, how is BOMBAY coded?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: 'ANLAZX', isCorrect: true },
            { text: 'ANLBZX', isCorrect: false },
            { text: 'BNLAZX', isCorrect: false },
            { text: 'ANLAZY', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-14',
        text: 'A man pointing to a photograph says, "The lady in the photograph is my nephew\'s maternal grandmother." How is the lady related to the man?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: 'Sister', isCorrect: false },
            { text: 'Sister-in-law', isCorrect: true },
            { text: 'Mother', isCorrect: false },
            { text: 'Wife', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-15',
        text: 'Complete the series: J2Z, K4Y, L7X, M11W, ?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: 'N16V', isCorrect: true },
            { text: 'N15V', isCorrect: false },
            { text: 'O16V', isCorrect: false },
            { text: 'N16U', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-l-16',
        text: 'If South-West becomes North, what does North-East become?',
        type: 'multiple-choice',
        category: 'logical',
        options: [
            { text: 'East', isCorrect: true },
            { text: 'West', isCorrect: false },
            { text: 'South', isCorrect: false },
            { text: 'South-East', isCorrect: false },
        ],
    },

    // VERBAL ABILITY (16 questions)
    {
        id: 'wipro-apt-v-1',
        text: 'Choose the synonym of "ELOQUENT":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Silent', isCorrect: false },
            { text: 'Articulate', isCorrect: true },
            { text: 'Awkward', isCorrect: false },
            { text: 'Hesitant', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-2',
        text: 'Choose the antonym of "OPTIMISTIC":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Hopeful', isCorrect: false },
            { text: 'Positive', isCorrect: false },
            { text: 'Pessimistic', isCorrect: true },
            { text: 'Cheerful', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-3',
        text: 'Fill in the blank: She has been working here _____ 2015.',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'from', isCorrect: false },
            { text: 'since', isCorrect: true },
            { text: 'for', isCorrect: false },
            { text: 'in', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-4',
        text: 'Identify the correctly spelled word:',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Accomodate', isCorrect: false },
            { text: 'Accommodate', isCorrect: true },
            { text: 'Acomodate', isCorrect: false },
            { text: 'Acommodate', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-5',
        text: 'What does "Bite the bullet" mean?',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'To eat quickly', isCorrect: false },
            { text: 'To face a difficult situation bravely', isCorrect: true },
            { text: 'To be aggressive', isCorrect: false },
            { text: 'To make a mistake', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-6',
        text: 'Choose the correct sentence:',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Each of the students have submitted their assignment.', isCorrect: false },
            { text: 'Each of the students has submitted their assignment.', isCorrect: true },
            { text: 'Each of the students have submitted his assignment.', isCorrect: false },
            { text: 'Each of the students are submitted their assignment.', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-7',
        text: 'Choose the synonym of "METICULOUS":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Careless', isCorrect: false },
            { text: 'Careful', isCorrect: true },
            { text: 'Hasty', isCorrect: false },
            { text: 'Rough', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-8',
        text: 'Fill in the blank: The committee _____ its decision yesterday.',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'announce', isCorrect: false },
            { text: 'announces', isCorrect: false },
            { text: 'announced', isCorrect: true },
            { text: 'announcing', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-9',
        text: 'Choose the antonym of "TRANSPARENT":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Clear', isCorrect: false },
            { text: 'Opaque', isCorrect: true },
            { text: 'Visible', isCorrect: false },
            { text: 'Bright', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-10',
        text: 'Identify the part of speech of the underlined word: The "beautiful" garden was full of flowers.',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Noun', isCorrect: false },
            { text: 'Verb', isCorrect: false },
            { text: 'Adjective', isCorrect: true },
            { text: 'Adverb', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-11',
        text: 'Choose the correct preposition: She is afraid _____ dogs.',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'from', isCorrect: false },
            { text: 'of', isCorrect: true },
            { text: 'with', isCorrect: false },
            { text: 'by', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-12',
        text: 'What is the plural of "Analysis"?',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Analysises', isCorrect: false },
            { text: 'Analyses', isCorrect: true },
            { text: 'Analysis', isCorrect: false },
            { text: 'Analysiss', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-13',
        text: 'Choose the synonym of "FRUGAL":',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Wasteful', isCorrect: false },
            { text: 'Economical', isCorrect: true },
            { text: 'Generous', isCorrect: false },
            { text: 'Extravagant', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-14',
        text: 'Fill in the blank: By next year, I _____ here for five years.',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'will work', isCorrect: false },
            { text: 'will be working', isCorrect: false },
            { text: 'will have been working', isCorrect: true },
            { text: 'would have worked', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-15',
        text: 'What does "Spill the beans" mean?',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'To make a mess', isCorrect: false },
            { text: 'To reveal a secret', isCorrect: true },
            { text: 'To cook food', isCorrect: false },
            { text: 'To waste something', isCorrect: false },
        ],
    },
    {
        id: 'wipro-apt-v-16',
        text: 'Choose the correctly punctuated sentence:',
        type: 'multiple-choice',
        category: 'verbal',
        options: [
            { text: 'Its a beautiful day.', isCorrect: false },
            { text: 'It\'s a beautiful day.', isCorrect: true },
            { text: 'Its\' a beautiful day.', isCorrect: false },
            { text: 'Its a beautiful day!', isCorrect: false },
        ],
    },
];
